# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
# 
# http://aws.amazon.com/apache2.0
# 
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

apiHandler:
  environment:
    APP_SM_WORKFLOW: ${self:custom.settings.workflowStateMachineArn}
    APP_WORKFLOW_ROLE_ARN: ${self:custom.settings.workflowLoopRunnerRoleArn}
    APP_WORKFLOW_SOLUTION_EVENTS_HANDLER_ARN: !GetAtt WorkflowSolutionEventsHandlerLambdaFunction.Arn

workflowSolutionEventsHandler:
  handler: src/lambdas/workflow-solution-events-handler/handler.handler
  role: RoleWorkflowSolutionEventsHandler
  tags: ${self:custom.tags}
  description: Handles events coming from the solution-wide EventBridge bus that are configured to trigger workflows
  environment:
    APP_SM_WORKFLOW: ${self:custom.settings.workflowStateMachineArn}
    APP_SOLUTION_EVENT_BUS_NAME: ${self:custom.settings.solutionEventBusName}

workflowLoopRunner:
  handler: src/lambdas/workflow-loop-runner/handler.handler
  role: RoleWorkflowLoopRunner
  timeout: 900 # 15 min
  tags: ${self:custom.tags}
  description: The workflow loop runner, it is expected to be invoked by AWS Step Functions and not directly
  environment:
    # We cannot use "!Ref SMWorkflow" below as that will create circular dependency
    APP_SM_WORKFLOW: ${self:custom.settings.workflowStateMachineArn}
    APP_PARAM_STORE_ROOT: ${self:custom.settings.paramStoreRoot}
    APP_PARAM_STORE_JWT_SECRET: ${self:custom.settings.paramStoreJwtSecret}
    APP_JWT_OPTIONS: ${self:custom.settings.jwtOptions}
    APP_ARTIFACTS_BUCKET_NAME: ${self:custom.settings.deploymentBucketName}
    APP_HOSTED_ZONE_ID: ${self:custom.settings.hostedZoneId}
    APP_DOMAIN_NAME: ${self:custom.settings.domainName}
    APP_API_URL: ${self:custom.settings.apiGatewayUrl}
