# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
# 
# http://aws.amazon.com/apache2.0
# 
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# ================================ Settings required by base-auth-cognito ===========================================
# Defines the email addresses of admin users who should be provisioned when Post Deployment
# runs. Admin details can be passed in a stringified JSON object where each item of the array
# defines the user's "email", "firstName", and "lastName".
# Example: [{"email": "admin@example.com", "firstName": "Example", "lastName": "Admin"}]
adminPrincipals: '[{"email": "admin@example.com", "firstName": "Example", "lastName": "Admin"}]'
