# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
# 
# http://aws.amazon.com/apache2.0
# 
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# The S3 bucket name to be used for S3 access logging and CloudTrail
# TODO: Avoid duplicating this from the base-ui component (probably
# by moving the logging bucket into a separate deployable unit)
loggingBucketName: ${self:custom.settings.globalNamespace}-logging

# ================================ DB Settings ===========================================

# DynamoDB table name for the deployment store
dbDeploymentStore: ${self:custom.settings.dbPrefix}-DeploymentStore

# Managed policy for using DynamoDB Encryption key.
# This is imported from the backend stack.
dynamoDbKmsAccessPolicyArn: ${cf:${self:custom.settings.backendStackName}.DynamoDbKmsAccessPolicyArn, ''}

# ================================ VPC ===========================================

# The stack name of the 'vpc' serverless service
vpcStackName: ${self:custom.settings.namespace}-vpc

# vpc and subnet(s) entries
vpcId: ${cf:${self:custom.settings.vpcStackName}.VpcId, ''}
publicSubnetIds: ${cf:${self:custom.settings.vpcStackName}.PublicSubnetIds, ''}
privateSubnetIds: ${cf:${self:custom.settings.vpcStackName}.PrivateSubnetIds, ''}
vpcDefaultSecurityGroupId: ${cf:${self:custom.settings.vpcStackName}.VpcDefaultSecurityGroupId, ''}
vpcApiGatewayEndpoint: ${cf:${self:custom.settings.vpcStackName}.VpcApiGatewayEndpoint, ''}

# ================================ IAM ===========================================

# The name of the IAM role created for the Lambda post deployment
postDeploymentRoleName: ${self:custom.settings.namespace}-PostDeployment

# The IAM role arn for the Lambda post deployment, we need to define it in the settings so it can be used in KMS key creation
postDeploymentRoleArn: 'arn:${AWS::Partition}:iam::${self:custom.settings.awsAccountInfo.awsAccountId}:role/${self:custom.settings.postDeploymentRoleName}'

# The stack name of the 'backend' serverless service
backendStackName: ${self:custom.settings.namespace}-backend

# ================================================================================

# If a config key from this object is absent in a final merged config/settings, throw an error with a message stated
# NOTE: this is needed per SDU
requiredSettings:
  useCmkDynamoDbEncryption: "Please add 'useCmkDynamoDbEncryption' to your config yaml file. Read more at components/base-post-deployment/INSTALLATION.md"
