# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
# 
# http://aws.amazon.com/apache2.0
# 
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

postDeployment:
  environment:
    # ================================ Settings required by base-auth-cognito ===========================================
    APP_USER_POOL_ID: ${cf:${self:custom.settings.backendStackName}.UserPoolId}
    APP_USER_POOL_CLIENT_ID: ${cf:${self:custom.settings.backendStackName}.UserPoolClientId}
    APP_USER_POOL_DOMAIN_PREFIX: ${cf:${self:custom.settings.backendStackName}.UserPoolDomainPrefix}
    APP_ADMIN_PRINCIPALS: ${self:custom.settings.adminPrincipals}
    APP_ENABLE_NATIVE_USER_POOL_USERS: ${self:custom.settings.enableNativeUserPoolUsers}
    APP_COGNITO_AUTH_N_PROVIDER_TITLE: ${self:custom.settings.cognitoAuthNProviderTitle}
    APP_WEBSITE_URL: ${cf:${self:custom.settings.webInfraStackName}.WebsiteUrl}
    APP_FED_IDP_IDS: ${self:custom.settings.fedIdpIds}
    APP_FED_IDP_NAMES: ${self:custom.settings.fedIdpNames}
    APP_FED_IDP_DISPLAY_NAMES: ${self:custom.settings.fedIdpDisplayNames}
    APP_FED_IDP_METADATAS: ${self:custom.settings.fedIdpMetadatas}
