# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
# 
# http://aws.amazon.com/apache2.0
# 
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# ================================ Custom Domains ===========================================

# The stack name of the 'customDomains' serverless service
customDomainsStackName: ${self:custom.settings.namespace}-customDomains

# Hosted zone ID for the custom domain
hostedZoneId: ${cf:${self:custom.settings.customDomainsStackName}.HostedZoneId, ''}

# Base domain name for the custom domain
baseDomainName: ${cf:${self:custom.settings.customDomainsStackName}.BaseDomainName, ''}

# Lambda backing for ACM certificate custom resource
acmCertificateCustomResourceLambdaArn: ${cf:${self:custom.settings.customDomainsStackName}.AcmCertificateCustomResourceLambdaArn}

# Domain name to use, if custom domains; must be subdomain (or same) as 'hostedZoneDomainName'
domainName: ${self:custom.settings.baseDomainName}

# Whether to provision WAF resources to allow for IP allow listing of access to the CloudFront website
useCloudFrontWaf: true

# This prefix is used for naming various WAF resources
wafNamespace: ${self:custom.settings.envName}${self:custom.settings.awsRegionShortName}${self:custom.settings.solutionName}
